alias HDMI="xrandr --output HDMI-1 --auto --right-of eDP-1"
alias VGA="xrandr --output VGA-1 --auto --right-of eDP-1"
alias off='xrandr --output HDMI-1 --off && xrandr --output VGA-1 --off'

alias mute="amixer sset Master mute"
alias unmute="amixer sset Master unmute"

set -x MIT "$HOME/MyBrain/BodySelf/FormalEducation/MIT"
set -x CMU "$HOME/MyBrain/BodySelf/FormalEducation/CMU"
set -x STANFORD "$HOME/MyBrain/BodySelf/FormalEducation/Stanford"
set -x FINANCES "$HOME/MyBrain/OutsideWorld/Finances/Finances"
set -x DIARY "$HOME/MyBrain/BrainSelf/Diary"
set -x MUSIC "$HOME/MyBrain/BrainSelf/Music"
set -x HEALTH "$HOME/MyBrain/BodySelf/Health"
set -x NUTRITION "$HOME/MyBrain/BodySelf/Health/Nutrition"
set -x SLEEP "$HOME/MyBrain/BodySelf/Health/Sleep"
set -x QUESTIONS "$HOME/MyBrain/BrainSelf/Questions"
set -x HABITS "$HOME/MyBrain/BodySelf/Habits"
set -x APPLICATIONS "$HOME/MyBrain/BodySelf/Career/Applications"
set -x EMPLOYMENT "$HOME/MyBrain/BodySelf/Career/Employment"
set -x TODO "$HOME/MyBrain/BrainSelf/ToDo"
set -x CS "$HOME/MyBrain/BrainSelf/ModelBuilding/Mathematics"
set -x CS "$HOME/MyBrain/BrainSelf/ModelBuilding/ComputerScience"
set -x PROG "$CS/Programming"
set -x NECSI "$EMPLOYMENT/NECSI"
set -x PROJECTS "$HOME/MyBrain/BrainSelf/Projects"
set -x NIX "$HOME/LocalSoftware/ConfigAndDotFiles/NixFiles"
set -x COQ "$PROG/TheoremProving/Coq"
set -x HOTT "$PROG/TheoremProving/HoTT"
set -x PROOFTREES "$COQ/ManipulateProofTrees"
set -x WEBSITE "$STANFORD/AllYears/www"
set -x SMT "$COQ/SMT"
set -x CS "$HOME/MyBrain/BrainSelf/ModelBuilding/ComputerScience"
set -x CS168 "$STANFORD/CS168"

set -x BARRETT "$STANFORD/Barrett"
set -x AIKEN "$STANFORD/Aiken"
set -x RE "$STANFORD/Re"


set -x PATH $PATH "$HOME/LocalSoftware/coq/bin"
set -x PATH $PATH "$HOME/LocalSoftware/agda/.stack-work/install/x86_64-linux/lts-13.3/8.6.3/bin"
set -x PATH $PATH "$HOME/LocalSoftware/exercism"
set -x PATH $PATH "$HOME/LocalSoftware/lean/bin"
set -x PATH $PATH "$HOME/.cabal/bin"
set -x PATH $PATH "$HOME/.cargo/bin"
set -x PATH $PATH "$HOME/LocalSoftware/CVC4/build/bin"
set -x PATH $PATH "$HOME/LocalSoftware/CVC4/lfsc-checker/build/src"


